Trust-Code/trustcode-addons

project_task_materials/__manifest__.py
project_task_materials/models/project_task.py
project_task_materials/views/task_materials.xml
project_task_materials_report/__manifest__.py

Alguns ajustes que fiz ontem para que possamos colocar o módulo em produção hoje

Ajustes para liberar produção

---

sale_order_contract/models/sale_order.py

Campo relacionado marcar como readonly.

---

royalties/security/ir.model.access.csv
stock_on_demand/models/stock_move.py

somente adicionei um variável para não correr o risco de execucar uma aquisição duas vezes. Isso estava acontecendo em função do cliente utilizar o objeto purchase.requisition.

10.0 filtro te stock on demand

---

project_task_materials/__manifest__.py
project_task_materials/models/project_task.py
stock_on_demand/__manifest__.py
stock_on_demand/models/stock_move.py

FIX - Corrige o cálculo da quantidade da regra de estoque por demanda
Leva em conta as movimentações reservadas, a quantidade em estoque, a aquisição
criada utiliza a diferença destes itens

Força reserva automática de itens requisitados em tarefas

---

stock_delivery_info/models/stock_picking.py

Corrige as quantidades dos produtos enviadas.

Envia json após confirmada a transferência.

---

product_special_fields/__manifest__.py
product_special_fields/models/product_template.py
product_special_fields/models/stock_move_line.py
product_special_fields/models/stock_production_lot.py
product_special_fields/views/product_template_views.xml
product_special_fields/views/stock_move_line_views.xml
product_special_fields/views/stock_production_lot_views.xml

Correção do nome do campo à pedido do cRiente

[FIX] iccd -> iccid

---

stock_delivery_info/models/stock_picking.py

Removido campo que não existe number_of_packages
Log de envio do json

Lança exceção caso não tenha configurado agrupador.

---

kk_sites/views/kk_sites.xml

Atualizado o nome do campo

---

kk_sites/views/kk_sites.xml

atribuido somente leitura ao campo cod_site_kk

---

kk_sites/models/kk_sites.py

retirado a atualização do endereço

---

kk_sites/views/kk_sites.xml

Não permite que estados seja criados

---

kk_sites/models/kk_sites.py

Campo cidade obrigatório

---

kk_sites/views/kk_sites.xml

<field name="district" placeholder="Bairro" />

Inserido o campo district na view

---

kk_sites/views/kk_sites.xml

Alterado string do campo cod_site_kk

---

kk_sites/models/kk_sites.py
kk_sites/views/kk_sites.xml

ajustes no modelo kk_sites.
Remover PR https://github.com/Trust-Code/trustcode-addons/pull/201 pois implementei isto aqui (e aqui funciona)

11.0 bug kk engenharia

---

account_cash_flow/__manifest__.py
account_cash_flow/models/cash_flow_report.py
sale_variant_configurator/models/sale_order.py

- Linhas com valores zerados agora são filtrados do relatório;
- Linhas originadas de vendas parceladas agora exibem o valor correto.

[10.0][FIX]Account cash flow

---

account_cash_flow/models/cash_flow_report.py

Pão, Céu, Linguiça!!!
Agradecimentos especiais ao Mr. Dan

[10.0]Agora vai

---

stock_json_api/controllers/main.py

Permite a criação de pickings somente nos picking types que estão setados na configuração.

[IMP] Configurações de criação de pickings

---

mrp_dynamic_bom/__init__.py
mrp_dynamic_bom/__manifest__.py
mrp_dynamic_bom/models/__init__.py
mrp_dynamic_bom/models/mrp_bom.py
mrp_dynamic_bom/models/mrp_production.py
mrp_dynamic_bom/security/ir.model.access.csv
mrp_dynamic_bom/views/mrp_dynamic_bom_views.xml

> Eu acredito que essa build não irá quebrar!

[KINDA FEAT] Dynamic lines for BoM

---

nota_debito/__manifest__.py
nota_debito/models/__init__.py
nota_debito/models/account_invoice.py
nota_debito/models/res_company.py
nota_debito/models/res_config.py
nota_debito/reports/nota_debito.xml
nota_debito/views/res_config.xml

Assim mencionado no titulo, foi adicionado sequencial para as notas de debito
Instruções:
1. Configuração:
- Contabilidade -> Configurações -> Sequencia da nota de debito
- Selecionar OU criar uma sequencia para a nota de debito
- Salvar
A impressão da nota de débito terá a sequencia dela no report apenas quando a sequencia estiver setada E o proprio invoice tiver seu numero na sequencia nova, ou seja, apenas as invoices geradas DEPOIS da instalação do modulo terão sua sequencia impressa no report.

Adicionado sequencial para a nota de debito

---

sale_order_expedition_notes/__init__.py
sale_order_expedition_notes/__manifest__.py
sale_order_expedition_notes/i18n/pt_BR.po
sale_order_expedition_notes/models/__init__.py
sale_order_expedition_notes/models/sale_order.py
sale_order_expedition_notes/models/stock_picking.py
sale_order_expedition_notes/views/sale_order_views.xml
sale_order_expedition_notes/views/stock_picking_views.xml

Sale Order Expedition Notes -> Stock Picking Expedition Notes

[11.0]Sale Order Expedition Notes

---

sale_variant_configurator/i18n/pt_BR.po
sale_variant_configurator/models/sale_order.py

- raise UserError when no product is found
- Translations added

[11.0]Sale Variant Configurator- UserError and translation added

---

oca_dependencies.txt
sale_order_line_additional_info/__init__.py
sale_order_line_additional_info/__manifest__.py
sale_order_line_additional_info/i18n/pt_BR.po
sale_order_line_additional_info/models/__init__.py
sale_order_line_additional_info/models/mrp_production.py
sale_order_line_additional_info/models/sale_order_line.py
sale_order_line_additional_info/views/mrp_production_view.xml
sale_order_line_additional_info/views/sale_order_line_views.xml
sale_order_line_additional_info/wizard/__init__.py
sale_order_line_additional_info/wizard/additional_info_wizard.py
sale_order_line_additional_info/wizard/additional_info_wizard_view.xml
sale_order_line_additional_info/wizard/product_configurator.py

additional field added to so.line and mrp.production
field can be set at the last step of product.configurator and when editing so.line

11.0 so line additional info

---

survey_page_observations/__init__.py
survey_page_observations/__manifest__.py
survey_page_observations/models/__init__.py
survey_page_observations/models/survey.py
survey_page_observations/views/survey_template.xml
survey_page_observations/views/survey_views.xml

Survey
- Observation fields added to:
- Question;
- Page;

[11.0]Survey Observations fields

---

bom_import/__init__.py
bom_import/__manifest__.py
bom_import/models/__init__.py
bom_import/models/mrp_bom.py
bom_import/models/mrp_production.py
bom_import/models/procurement_rule.py
bom_import/models/stock_move.py
bom_import/views/mrp_production.xml
bom_import/views/stock_move.xml
bom_import/wizard/bom_import_wizard.py

All XML information is now being copied to BoM and BoM lines.
changed VIDROS to VIDRO... wrong dir

11.0 bom import more info

---

payment_report/__init__.py
payment_report/__manifest__.py
payment_report/models/__init__.py
payment_report/models/account_payment.py
payment_report/reports/account_payment_reports.xml
payment_report/views/account_payment_views.xml

Report added for the model account.payment

[FEAT]Added account.payment report layout

---

serial_number_nfe/models/sale_order.py

Uses stock.move and stock.production.lot to add maturity date and serial number/lot into DANFE

add serial number/lot info and life date to danfe

---

purchase_kits/__init__.py
purchase_kits/__manifest__.py
purchase_kits/models/__init__.py
purchase_kits/models/purchase_kit.py
purchase_kits/models/purchase_order.py
purchase_kits/views/purchase_order.xml

Módulo especial para gerenciar kits nas compras

11.0 purchase kits

---

payment_report/models/account_payment.py
payment_report/reports/account_payment_reports.xml

Company name moved from table to header

Payments grouped by company and user; 

---

kk_art/views/project.xml

nao sei pq nao tinha dado erro antes... meh

colocando o filter pro começo do arquivo

---

kk_art/models/project.py
kk_sites/models/project.py

colocando compute no campo art

---

.gitignore
contract/models/contract.py
contract/models/contract_line.py

[MIG] contract

---

contract/models/contract_line.py

[FIX] contract
